### ISSUE TITLE
Pipelining support

### ISSUE THREAD

**Issue by dolzenko** [EverythingMe/go-disque#8]
Hi Dvir, thank you for sharing this lib!

Do you have any plans to add pipelining support to the disque client? My use case is streaming massive amount of jobs, so I assume it should work similarly to e.g. redigo pipelining with Send/Flush/Receive flow.

**Comment by dvirsky** [comment]
Hi! Pipelining is a good idea indeed, and not too hard to implement. However I'm not sure I'll have the time in the near future to implement it. Any chance you can implement this? I'll guide you in what's the easiest way to do it  IMO. It shouldn't take much work

**Comment by dolzenko** [comment]
I can give it a try, so what kind API do you envision?

**Comment by dolzenko** [comment]
@dvirsky drafted something in https://github.com/EverythingMe/go-disque/pull/9

**Comment by dolzenko** [comment]
Added in https://github.com/EverythingMe/go-disque/commit/87ef61a83c98923dfd9048f9fb80eca789e5d3c9 . Thanks a lot :+1:
